import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LangburpProvider } from "@langburp/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (!process.env.NEXT_PUBLIC_LANGBURP_PUBLIC_API_KEY) {
    throw new Error("LANGBURP_PUBLIC_API_KEY is not set");
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LangburpProvider
          publicApiKey={process.env.NEXT_PUBLIC_LANGBURP_PUBLIC_API_KEY}
          apiBaseUrl={process.env.NEXT_PUBLIC_LANGBURP_API_BASE_URL} // Optional, defaults to https://api.langburp.com
        >
          {children}
        </LangburpProvider>
      </body>
    </html>
  );
}
